defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  402b359e-759c-4938-b279-b9a22b2c6d6a: # Craft CMS Starter
    enabledByDefault: true
    hasUrls: true
    template: _pages/interior_about.twig
    uriFormat: about
type: single
