defaultPlacement: end
enableVersioning: false
handle: siteNavigation
name: 'Site Navigation'
propagationMethod: all
siteSettings:
  402b359e-759c-4938-b279-b9a22b2c6d6a: # Craft CMS Starter
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: fc27e15d-38df-4797-8e04-7f9790a90d45
type: structure
